on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        run: yarn lint

      - name: Run tests
        run: yarn test:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2

      - name: Release dry-run
        run: yarn release:test
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3

      - name: Use latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Configure CI Git User
        run: |
          git config --global user.email codex2r@gmail.com
          git config --global user.name josex2r

      - name: Release
        run: yarn release
        env:
          HUSKY: 0
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
